@startuml

participant "Cron" as cron
participant "GitHub PR" as ghPr
participant "OpenShift4" as bootstrap
participant "Trigger Service" as trigger
participant "Pipeline CI" as pipelineCI

== Cron Install bootstrap cluster ==
autonumber

cron->bootstrap: Cleanup old OpenShift4 cluster install
cron->bootstrap: BootStrap Temporary OpenShift4 cluster
bootstrap<-cron: Check until installed
cron->bootstrap: Install TektonCD Pipeline/Triggers

== Start Nightly CI PR ==
autonumber

cron->ghPr: Nightly PR gets created for validating nightly CI
ghPr->bootstrap: Github Webhook Postback to OpenShift Route
bootstrap->trigger: Webhook event to TektonCD Trigger route and service
trigger->pipelineCI: Trigger create a PipelineRun for CI

@enduml
