---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: openshift-pipeline-ci

spec:
  params:
    - name: UPLOADER_HOST
    - name: IMAGE_NAME
    - name: CLUSTER_NAME

  resources:
    - name: plumbing-git
      type: git
    - name: tektoncd-pipeline-git
      type: git
    - name: bootstrap-image
      type: image

  tasks:

  - name: build-bootstrap
    taskRef:
      name: buildah
    resources:
      inputs:
        - name: source
          resource: plumbing-git
      outputs:
        - name: image
          resource: bootstrap-image
    params:
      - name: DOCKERFILE
        value: CI/bootstrap/Dockerfile

  - name: install-openshift4-cluster
    taskRef:
      name: openshift4-install
    runAfter: [build-bootstrap]
    resources:
      inputs:
        - name: plumbing-git
          resource: plumbing-git
    params:
      - name: IMAGE_NAME
        value: $(params.IMAGE_NAME)
      - name: UPLOADER_HOST
        value: $(params.UPLOADER_HOST)

  - name: build-pipeline-and-push
    taskRef:
      name: build-tektoncd-pipeline-and-push
    runAfter: [install-openshift4-cluster]
    resources:
      inputs:
        - name: plumbing-git
          resource: plumbing-git
        - name: tektoncd-pipeline-git
          resource: tektoncd-pipeline-git
    params:
      - name: UPLOADER_HOST
        value: $(params.UPLOADER_HOST)

  - name: pipeline-test
    taskRef:
      name: pipeline-test
    runAfter: [build-pipeline-and-push]
    resources:
      inputs:
        - name: plumbing-git
          resource: plumbing-git
        - name: tektoncd-pipeline-git
          resource: tektoncd-pipeline-git
    params:
      - name: IMAGE_NAME
        value: $(params.IMAGE_NAME)
      - name: UPLOADER_HOST
        value: $(params.UPLOADER_HOST)
      - name: CLUSTER_NAME
        value: $(params.CLUSTER_NAME)
